### ISSUE TITLE
Just did a pull, 1 test passes, 7 failed

### ISSUE THREAD

**Issue by ThomasCorbin** [LukeMathWalker/tracing-bunyan-formatter#26]
It looks like the json formatting isn't working.  The beginning open curly brace isn't there.  Lines start like this:

"v":0,"name":"test","msg":"[SHAVING_YAKS - START]"

So that deserializing with serde fails.

I also had to modify two lines in the e2e file to make the test compile.   I think what I did to make it compile "works", but is heinous and ugly and stupid, so I won't bother you with that.

I'm using rust 1.66

**Comment by ThomasCorbin** [comment]
Oh, and it all comes out on one line so that the bunyan command doesn't work.
I edited my logfile to add a newline and the initial curly brace before each "v" and bunyan now seems to work.

**Comment by ThomasCorbin** [comment]
Ok, this works for me, probably not the best idea, but maybe it will shortcut your investigation.  I changed the emit function to this:

        // buffer.write_all(b"\n")?;
        self.make_writer.make_writer().write_all(&buffer)?;
        self.make_writer.make_writer().write_all(b"\n")

That buffer.write_all somehow shifted the buffer so that the "{" fell off the front, but the newline didn't show up, which is weird, and means I don't understand.

**Comment by LukeMathWalker** [comment]
Thanks for reporting the issue - I yanked the last release and I'll start investigating 👌🏻

**Comment by LukeMathWalker** [comment]
This innocent-looking commit is the culprit: https://github.com/LukeMathWalker/tracing-bunyan-formatter/commit/710d9bf5e2394dd9e469d5a3e047fbfc0146bfbd

The `Write` implementation on a slice _replaces_ the content of the slice with what you are trying to write, instead of appending it, as the `Vec<u8>` implementation does.
Hence the newline replacing the opening brace.

I fixed the issue and I should be cutting a new release soon.
